# Generated by Django 4.2.29 on 2026-03-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Localisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(default="Abidjan", max_length=100)),
                ("pays", models.CharField(default="Côte d'Ivoire", max_length=100)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("google_maps_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Localisation",
                "verbose_name_plural": "Localisations",
            },
        ),
        migrations.CreateModel(
            name="PriseDeContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("sujet", models.CharField(blank=True, max_length=250, null=True)),
                ("message", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("lu", "Lu"),
                            ("repondu", "Répondu"),
                            ("archive", "Archivé"),
                        ],
                        default="nouveau",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("date_envoi", models.DateTimeField(auto_now_add=True)),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Prise de Contact",
                "verbose_name_plural": "Prises de Contact",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("titre", models.CharField(max_length=200)),
                ("sous_titre", models.CharField(blank=True, max_length=300, null=True)),
                ("bio", models.TextField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profil/"),
                ),
                ("cv", models.FileField(blank=True, null=True, upload_to="cv/")),
                ("disponible", models.BooleanField(default=True)),
                ("annees_experience", models.PositiveIntegerField(default=3)),
                ("nombre_projets", models.PositiveIntegerField(default=10)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "localisation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utilisateur",
                        to="api.localisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("backend", "⚙️"),
                            ("frontend", "🎨"),
                            ("data", "📊"),
                            ("security", "🔒"),
                            ("devops", "🐳"),
                            ("mobile", "📱"),
                            ("autre", "💡"),
                        ],
                        default="autre",
                        max_length=50,
                    ),
                ),
                ("numero", models.PositiveIntegerField(default=1)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="api.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="ReseauSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plateforme",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter / X"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("portfolio", "Portfolio"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Classe CSS ou nom d'icône",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reseaux_sociaux",
                        to="api.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réseau Social",
                "verbose_name_plural": "Réseaux Sociaux",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description_courte", models.CharField(max_length=300)),
                ("description_longue", models.TextField(blank=True, null=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("fullstack", "Full-Stack"),
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("data", "Data & ML"),
                            ("odoo", "Odoo / ERP"),
                            ("mobile", "Mobile"),
                            ("autre", "Autre"),
                        ],
                        default="fullstack",
                        max_length=50,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("archive", "Archivé"),
                        ],
                        default="termine",
                        max_length=20,
                    ),
                ),
                (
                    "technologies",
                    models.JSONField(
                        default=list, help_text="Liste des technologies utilisées"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projets/"),
                ),
                ("url_github", models.URLField(blank=True, null=True)),
                ("url_live", models.URLField(blank=True, null=True)),
                ("url_demo", models.URLField(blank=True, null=True)),
                ("en_vedette", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projets",
                        to="api.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["ordre", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("education", "Formation"),
                            ("professionnel", "Professionnel"),
                            ("projet", "Projet"),
                            ("competition", "Compétition"),
                            ("certification", "Certification"),
                        ],
                        default="professionnel",
                        max_length=30,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("organisation", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_debut", models.CharField(max_length=50)),
                ("date_fin", models.CharField(blank=True, max_length=50, null=True)),
                ("lieu", models.CharField(blank=True, max_length=150, null=True)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "actuel",
                    models.BooleanField(default=False, help_text="Expérience en cours"),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="api.utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expérience",
                "verbose_name_plural": "Expériences",
                "ordering": ["-ordre"],
            },
        ),
    ]
